language: php
php:
  - 7.2.5
  - 5.4.0
install:
  - composer self-update
  - composer install --prefer-dist --no-interaction
  - composer info --all
before_script:
  - mysql -e 'create database yii2_workflow_test;'
  - cd tests
  - php ./codeception/bin/yii  migrate/up --interactive=0
  - ../vendor/bin/codecept build

script: ../vendor/bin/codecept run unit
